name: Master Branch

on:
  push:
    branches:
      - 'master'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test

  push-docker:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04
    needs: [test]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build docker image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build . -f src/main/docker/Dockerfile.native.multiarch -t qiot-hackfest-management-service:latest
      - name: Push docker image to Docker Hub
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login docker.io -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
          docker tag qiot-hackfest-management-service:latest docker.io/bentaljaard/air-quality-management:aarch64-latest
          docker push docker.io/bentaljaard/air-quality-management:aarch64-latest
